services:
  test:
    image: nvidia/cuda:11.6.2-cudnn8-devel-ubuntu20.04
    command: nvidia-smi
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
